spring.application.name=cadastro-usuarios-backend

# ---- Banco de dados PostgreSQL ----
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ---- JWT ----
jwt.secret=
jwt.expiration-ms=

# ---- ViaCEP ----
viacep.base-url=https://viacep.com.br/ws

# ---- Cache (Caffeine) ----
spring.cache.type=caffeine
spring.cache.cache-names=cepCache
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=24h

server.port=${PORT:8080}
